name = "test-d"
type = "webpack"
workers_dev = false
route="https://*.asksumo.com/*"
zone_id = "876b2012bec91ee930fd61a80094715e"
account_id = "2d4690bfb50a2c0455b74dc36b5c6a14"

[site]
bucket = "./public"
entry-point = "workers-site"
