account_id = "2d4690bfb50a2c0455b74dc36b5c6a14"
name = "test"
type = "webpack"
workers_dev = true

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
name = "docs-site"
route="https://*.asksumo.com/*"
zone_id = "876b2012bec91ee930fd61a80094715e"
account_id = "2d4690bfb50a2c0455b74dc36b5c6a14"
