name = "test"
type = "webpack"

account_id = "2d4690bfb50a2c0455b74dc36b5c6a14"
zone_id = "876b2012bec91ee930fd61a80094715e"

route="https://*.asksumo.com/*"
workers_dev = false

[site]
bucket = "./public"
entry-point = "workers-site"
workers_dev = false
